# Licensed under the Apache License, Version 2.0 (the "License"); Copyright 2025 Piyush Joshi
version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    command: start-dev --import-realm
    environment:
      KC_HTTP_PORT: 8081
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8081"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import


