# Licensed under the Apache License, Version 2.0 (the "License"); Copyright 2025 Piyush Joshi
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'
      - name: Build and test
        run: mvn -B -ntp -DskipTests=false clean verify


